-- À exécuter après schema.sql pour reprendre les ressources déjà décrites sur le site.
-- (Les liens '#' sont des placeholders à remplacer via l'admin une fois les vrais documents/URLs disponibles.)

insert into ressources (id, gt, genre, origine, date, duree, titre, texte, lien) values
  ('mima-note-cadrage', 'mima', 'document', 'gt', 'mai 2026', NULL, 'Note de cadrage du groupe de travail', 'Le mandat, la composition et le calendrier des travaux.', '#'),
  ('mima-parcours-transition', 'mima', 'presentation', 'gt', 'juin 2026', '12 min', 'Le parcours de transition, pas à pas', 'Présentation animée du passage d''un dispositif à l''autre.', '#'),
  ('penibilite-etat-des-lieux', 'penibilite', 'document', 'gt', 'avril 2026', NULL, 'État des lieux de la pénibilité dans les unités', 'Synthèse des constats remontés par les institutions participantes.', '#'),
  ('penibilite-restitution-copil', 'penibilite', 'video', 'gt', 'juin 2026', '18 min', 'Restitution au comité de pilotage', 'Les premières pistes de mesures, présentées et commentées.', '#'),
  ('violence-recensement', 'violence', 'document', 'gt', 'février 2026', NULL, 'Recensement de bonnes pratiques — Concept d’accompagnement et gestion de la violence', 'Le document de référence issu du GT, construit à partir de l''expérience de terrain et de repères scientifiques (standard grison, HAS, lignes directrices HEVE).', '#'),
  ('violence-checklist', 'violence', 'document', 'gt', 'février 2026', NULL, 'Check-list pour l’accompagnement des personnes en situation complexe', 'L''outil d''autoévaluation complémentaire au recensement, organisé par grands axes : partenariat, transitions, prévention, désescalade, suivi, coordination.', '#'),
  ('violence-ext-icp', 'violence', 'lien', 'externe', '', NULL, 'ICP — intervention de crise et prévention', 'Interventions d''urgence sous 24h, soutien psychologique individuel et collectif, personne de confiance externe, formations en premiers secours émotionnels.', 'https://www.i-c-p.ch/concept'),
  ('violence-ext-unisante', 'violence', 'lien', 'externe', '', NULL, 'Unisanté — Prévention et gestion des risques psychosociaux au travail', 'Diagnostic RPS, formations, consultations individuelles et soutien post-événement traumatique pour les équipes.', 'https://www.unisante.ch/prevention-gestion-risques-psychosociaux'),
  ('violence-ext-oit', 'violence', 'lien', 'externe', '', NULL, 'OIT — Stress au travail et santé mentale', 'Repères de l''Organisation internationale du travail sur la prévention du stress chronique et la santé mentale au travail.', 'https://www.ilo.org/wcmsp5/groups/public/---ed_protect/---protrav/---safework/documents/publication/wcms_748323.pdf'),
  ('violence-ext-standard-grison', 'violence', 'lien', 'externe', '', NULL, 'Standard grison', 'Instrument de référence pour la prévention, la saisie et le traitement des transgressions de limites en contexte organisé.', '#'),
  ('violence-ext-has', 'violence', 'lien', 'externe', '', NULL, 'Haute Autorité de Santé (HAS)', 'Recommandations de bonnes pratiques professionnelles dans le champ médico-social, dont la prévention des comportements-défis.', '#'),
  ('violence-ext-heve', 'violence', 'lien', 'externe', '', NULL, 'HEVE — Lignes directrices pour la gestion des comportements-défis', 'Cadre méthodologique (Suisse alémanique) pour l''accompagnement des personnes présentant des comportements-défis.', 'https://www.fhnw.ch/plattformen/heve/leitlinien/'),
  ('formation-catalogue-base', 'formation', 'document', 'gt', 'mise à jour continue', NULL, 'Catalogue des formations continues de base', 'Les formations d’introduction à l’autisme et aux troubles du spectre autistique proposées par les partenaires de formation du canton.', '#'),
  ('formation-catalogue-specifique', 'formation', 'document', 'gt', 'mise à jour continue', NULL, 'Catalogue des formations continues spécifiques', 'Les formations avancées et certifiantes sur les comportements-défis, la gestion de crise et la violence interpersonnelle.', '#');
